#!/usr/bin/env bash
# Reconstruct the project from immutable upstream + one cumulative patch + overlay.
# This assembler intentionally performs no compile, test, CUDA, or training work.
set -euo pipefail
HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
DEST=${1:?Usage: bash scripts/bootstrap.sh /absolute/new/GeoTrack-GS}
REF=81ada6a32c918591ae7c7a0279dc6ca7a8018e2f
[[ ! -e "$DEST" ]] || { echo 'Destination must not exist. Your existing work is never overwritten.' >&2; exit 2; }
git clone --no-checkout https://github.com/CPy255/GeoTrack-GS.git "$DEST"
git -C "$DEST" config core.autocrlf false
git -C "$DEST" checkout --detach "$REF"
[[ "$(git -C "$DEST" rev-parse HEAD)" == "$REF" ]] || {
  echo 'Pinned upstream checkout did not resolve to the required commit.' >&2
  exit 2
}
git -C "$DEST" submodule update --init --recursive
# The patch is generated from this exact pre-AST base.  Keep `git apply --check`
# immediately before application: the AST integration below must never be used to
# hide a drifting patch or a post-integration patch generated by mistake.
git -C "$DEST" apply --check "$HERE/patches/phase2_1_integrity.patch"
git -C "$DEST" apply "$HERE/patches/phase2_1_integrity.patch"
# Overlay the current research modules before applying the guarded integration
# transformations.  The copied integration script is invoked from DEST so it
# sees exactly the files that will be used by the assembled checkout.
for dir in diffusion_guidance geometric_constraints tools tests configs; do
  [[ -d "$HERE/$dir" ]] || { echo "Missing package overlay directory: $HERE/$dir" >&2; exit 2; }
  mkdir -p "$DEST/$dir"; cp -a "$HERE/$dir/." "$DEST/$dir/"
done
mkdir -p "$DEST/research_scripts"
cp -a "$HERE/scripts/." "$DEST/research_scripts/"
[[ -f "$DEST/research_scripts/apply_integration_fixes.py" ]] || {
  echo 'Missing guarded integration script after overlay copy.' >&2
  exit 2
}
python "$DEST/research_scripts/apply_integration_fixes.py" "$DEST"
cp "$HERE/requirements-"*.txt "$DEST/"
if [[ -d "$HERE/../docs" ]]; then
  mkdir -p "$DEST/research_docs"
  cp -a "$HERE/../docs/." "$DEST/research_docs/"
fi
printf '\nAssembled source only: %s\nNo compile, CPU, CUDA, or training checks were run. Follow research_docs/FERN_PRECHECK_AND_RUN.md, beginning with the explicit environment gate.\n' "$DEST"
